name: Publish to npm

on:
  push:
    branches:
      - master    

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm run build
      - run: npm publish --access=public
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Status
        if: failure() || cancelled()
        run: echo "Modlue not published to NPM"
