name: Publish to npm

on:
  push:
    branches:
      - master    

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm i
      - run: npm run docs
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: "docs: Generated documentation"
  publish-npm:
    needs: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm run build
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
